### ISSUE TITLE
Missing release tags

### ISSUE THREAD

**Issue by ebourg** [FasterXML/jackson-1#7]
The repository is missing many release tags. If I'm not mistaken here are the commits for the 1.9.x releases:

    git tag 1.9.13 3225405abf68a318b6f21e9ccf7d5c00e80e4df4
    git tag 1.9.12 2b6f4d4fb79cd77e53499870c50ab5cdc0ddb977
    git tag 1.9.11 d1c26ec538a8701cff7548009254fd6183b71873
    git tag 1.9.10 c971d99794ff3c9422ee7624a11f429932324aed
    git tag 1.9.9 39ae7c25faef30f8738735135a1580c686364b86
    git tag 1.9.8 dd4c844351db8875868830e57b111975c4d87b49
    git tag 1.9.7 e5a1a5ae7618b698c5e4d56a65e659aa61d92f98
    git tag 1.9.6 714931ef6e8248c08913d6f42def755dab233e42
    git tag 1.9.5 9eb25fdf2bb503a2594e35a77c37b7420e8b2fe0
    git tag 1.9.4 86b2b959dd1ab3c1846bcf4b66140b7f2b9d00a7
    git tag 1.9.3 18d390553ceb28855a97704bec889d864c186f13
    git tag 1.9.2 85a56d3c81be77e3208325d32375676a1e0e073b
    git tag 1.9.1 c421be78f6ae88f30600de34b9b22ab46f6653cc

**Comment by cowtowncoder** [comment]
Jackson 1.x releases were done using Ant maven task, and manual tagging was probably omitted back then (except for new minor releases). Thank you for reverse engineering tags, I added them.

**Comment by ebourg** [comment]
Thank you!
